name: Build and Test with Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build and start Docker Compose services
    - name: Build and start services
      run: |
        docker-compose down --volumes
        docker-compose up --build -d

    # Step 4: Wait for services to be ready
    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if docker exec mysql mysqladmin ping -u root -proot --silent; then
            echo "MySQL is ready!"
            exit 0
          fi
          echo "Waiting for MySQL..."
          sleep 2
        done
        echo "MySQL did not become ready in time."
        exit 1

    # Step 5: Run application tests
    - name: Run tests
      run: |
        docker logs onlinebookstore_app
        # Add your test commands here, e.g., curl or integration tests

    # Step 6: Tear down Docker Compose
    - name: Tear down services
      if: always()
      run: docker-compose down --volumes
